### PR TITLE
Added possibility of ignore PDFTK warnings.

### PR DESCRIPTION
**Pull request by estacioneto**
I had to do it in a project and I think it could be useful to someone else :)

### CODE REVIEW

**Comment by estacioneto** [comment]
I removed the `this._cleanUpTempFiles();` in the error handler because it was called twice (in the error handler and the 'close' handler).

**Comment by jjwilly16** [comment]
I like it. Merging.

Thanks @estacioneto

**Comment by estacioneto** [comment]
Thanks for merging, @jjwilly16 ! When will be the next release?

**Comment by jjwilly16** [comment]
I’ll get it out late tonight. I have a few other small things to straighten out. It’ll be on npm in the morning. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by estacioneto** [comment]
Got it, @jjwilly16 !

**Pull request merged**
